// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqVI-w1TCnMxeCvnnTzqi_FAz6GsYXuWo',
    appId: '1:62159362051:web:0e187153cc0f2f61055636',
    messagingSenderId: '62159362051',
    projectId: 'uas-net-l',
    authDomain: 'uas-net-l.firebaseapp.com',
    storageBucket: 'uas-net-l.appspot.com',
    measurementId: 'G-BMMW54SH79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95OM6v9bbmtA9amlzw83s1lrUed3kBOs',
    appId: '1:62159362051:android:d6ac7227843c562a055636',
    messagingSenderId: '62159362051',
    projectId: 'uas-net-l',
    storageBucket: 'uas-net-l.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNh76cUghTGMSjkxrIgXYo2sLLsJu0rp0',
    appId: '1:62159362051:ios:268bc682dced60eb055636',
    messagingSenderId: '62159362051',
    projectId: 'uas-net-l',
    storageBucket: 'uas-net-l.appspot.com',
    iosBundleId: 'com.example.uasNet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNh76cUghTGMSjkxrIgXYo2sLLsJu0rp0',
    appId: '1:62159362051:ios:db79abd6a29c5a62055636',
    messagingSenderId: '62159362051',
    projectId: 'uas-net-l',
    storageBucket: 'uas-net-l.appspot.com',
    iosBundleId: 'com.example.uasNet.RunnerTests',
  );
}
